// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VersionIncreaser
{
    internal sealed partial class Vsix
    {
        public const string Id = "VersionIncreaser.9c82006d-af04-4844-9c50-14ce6f6f0c9d";
        public const string Name = "VersionIncreaser";
        public const string Description = @".NET MAUI Version Increaser before publishing to appstore.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "GBD";
        public const string Tags = "Version";
    }
}
