// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VersionIncreaser
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VersionIncreaserString = "0b317ed6-b308-47d4-b6f0-4b478b06f147";
        public static Guid VersionIncreaser = new Guid(VersionIncreaserString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
        public const int ToolbarID = 0x1000;
        public const int ToolbarGroupID = 0x1001;
        public const int ContextMenuGroupID = 0x0200;
        public const int cmdidWindowsMedia = 0x0100;
        public const int cmdidWindowsMediaOpen = 0x0132;
    }
}